#!/usr/bin/env bash

set -e -o pipefail

build_aci() {
	local OPT
	OPT="--work-path $(mktemp)"
	test -z "$ACIPATH" || ACIPATH=$(mktemp)
	test -z "$DEBUG" || OPT="$OPT --debug"
	acbuild $OPT begin
	echo "build_aci is done."
}
