#!/bin/sh
set -e

PGDATA="/var/lib/postgresql/9.4/data"

if [[ ! -d $PGDATA/base ]]; then
    head -c 25 /dev/urandom | base64 | head -c 32 > /pg-passwd
	echo "PG_PASSWORD=$(cat /pg-passwd)"
	mkdir -p $PGDATA
	chmod 0700 $PGDATA
	chown postgres:postgres -fR $PGDATA
    su postgres -s /usr/bin/initdb -- --pgdata=$PGDATA --pwfile=/pg-passwd --username=postgres --auth=trust >/dev/null
    rm /pg-passwd
fi

su postgres -s /usr/bin/postgres -- \
    -D $PGDATA \
    -c config_file=/etc/postgresql/9.4/main/postgresql.conf \
    -c hba_file=/etc/postgresql/9.4/main/pg_hba.conf
