#!/bin/sh
set -e -o pipefail

PGDATA="/var/lib/postgresql/9.4/data"

if [[ ! -d $PGDATA/base ]]; then
	P=$(mktemp)
	test -z "$PGPASSWORD" && PGPASSWORD=$(head -c 25 /dev/urandom | base64 | head -c 32) && echo PGPASSWORD=$PGPASSWORD
	echo -n $PGPASSWORD > $P
	mkdir -p $PGDATA
	chmod 0700 $PGDATA
	chown postgres:postgres -fR $PGDATA
	su postgres -s /usr/bin/initdb -- --pgdata=$PGDATA --pwfile=$P --username=postgres --auth=trust >/dev/null
	rm -f $P
fi

su postgres -s /usr/bin/postgres -- \
	-D $PGDATA \
	-c config_file=/etc/postgresql/9.4/main/postgresql.conf \
	-c hba_file=/etc/postgresql/9.4/main/pg_hba.conf
