#!/usr/bin/env bash
set -e

if [ "$EUID" -ne 0 ]; then
    echo "This script uses functionality which requires root privileges"
    exit 1
fi

# Start the build with an empty ACI
acbuild --debug begin

# In the event of the script exiting, end the build
acbuildEnd() {
    export EXIT=$?
    acbuild --debug end && exit $EXIT 
}
trap acbuildEnd EXIT

# Name the ACI
acbuild --debug set-name namsral.com/nginx

# Based on alpine
acbuild --debug dep add quay.io/coreos/alpine-sh

# Install nginx
acbuild --debug run apk update
acbuild --debug run apk add nginx

# Add a port for http traffic over port 80
acbuild --debug port add http tcp 80

# Add a mount point for files to serve
acbuild --debug mount add www /usr/share/nginx/www

# Add a mount point for additional configuration
acbuild --debug mount add confd /etc/nginx/conf.d

# Copy files
acbuild --debug copy ./extra/nginx.conf /etc/nginx/nginx.conf

# Run nginx in the foreground
acbuild --debug set-exec -- /usr/sbin/nginx -g "daemon off;"

test -n "$ACIPATH" || ACIPATH=nginx-latest-linux-amd64.aci
acbuild --debug write $ACIPATH

# Print the manifest
acbuild --debug cat-manifest
